title: Representing positive integers in binary
hero_image: images/banner.png
description: Learn how to represent a positive integer using 8-bit binary
original_url:
theme: red # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 1 # possible values: 1, 2 or 3
listed: false
ingredient: true
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: ""
technologies: ""
site_areas:
steps:
  - title: Positive integers in binary
